import type { MetadataRoute } from "next";

// PWA manifest (doc 01 §App shell & PWA). No service worker in v1 — PROPOSED
// (spec-silent): a money app must never show cached balances; Chrome no
// longer requires offline support for installability and iOS ignores service
// workers for install anyway. Icons are generated by scripts/gen-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Retenix",
    short_name: "Retenix",
    description: "A self-custodial brokerage run by agents you can read.",
    id: "/",
    start_url: "/home",
    display: "standalone",
    background_color: "#0b0e11", // graphite-950
    theme_color: "#0b0e11", // paper-50 variant flows through the viewport themeColor
    icons: [
      { src: "/icons/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icons/icon-512.png", sizes: "512x512", type: "image/png" },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
