// SPDX-License-Identifier: MIT
pragma solidity ^0.8.26;

import {RetenixPolicy} from "../src/RetenixPolicy.sol";
import {PolicyTestBase} from "./PolicyTestBase.sol";

/// Family 6 — cross-implementation vectors: the TS side (packages/registry
/// assetListHash/assetIdHash + packages/shared policy-digest) and the Solidity
/// side must agree byte-for-byte. Fixtures are generated by the registry
/// package's `gen:vectors` script — regenerate, never hand-edit.
///
/// The end-to-end tests are the strongest form: the REAL contract bytecode is
/// planted at the fixture domain address on the fixture chain id, and the
/// TS-produced signatures are submitted to it. Any encoding drift anywhere in
/// the chain (abi.encode layout, EIP-191 prefix, hash preimage) reverts.
contract CrossImpl is PolicyTestBase {
    string internal json;
    address internal fixtureSigner;
    address internal fixtureAgent;

    function setUp() public override {
        super.setUp();
        json = vm.readFile("test/fixtures/policy-vectors.json");
        fixtureSigner = vm.parseJsonAddress(json, ".signer");
        fixtureAgent = vm.parseJsonAddress(json, ".createPlan.agent");
        // plant the real contract at the fixture domain (agent from fixtures;
        // keeper/relayer irrelevant to these flows)
        address at = vm.parseJsonAddress(json, ".domain.contract");
        deployCodeTo(
            "RetenixPolicy.sol:RetenixPolicy",
            abi.encode(fixtureAgent, keeper, relayer, uint64(60)),
            at
        );
        policy = RetenixPolicy(at);
        vm.chainId(vm.parseJsonUint(json, ".domain.chainId"));
    }

    // --- assetIdHash: keccak(utf8(id)) ---
    function test_assetIdHashesMatch() public view {
        assertEq(keccak256("spyx"), vm.parseJsonBytes32(json, ".assetIdHashes.spyx"));
        assertEq(keccak256("tslax"), vm.parseJsonBytes32(json, ".assetIdHashes.tslax"));
        assertEq(keccak256("sol"), vm.parseJsonBytes32(json, ".assetIdHashes.sol"));
        assertEq(keccak256("memecoin"), vm.parseJsonBytes32(json, ".assetIdHashes.memecoin"));
    }

    // --- assetListHash: keccak(sorted ids joined with "|") ---
    function test_listHashesMatch() public view {
        assertEq(keccak256(joinIds(demoIds())), vm.parseJsonBytes32(json, ".listHashes.demo"));
        // TS sorts internally — shuffled input hashes identically
        assertEq(
            vm.parseJsonBytes32(json, ".listHashes.demoShuffledInput"),
            vm.parseJsonBytes32(json, ".listHashes.demo")
        );
        string[] memory one = new string[](1);
        one[0] = "spyx";
        assertEq(keccak256(joinIds(one)), vm.parseJsonBytes32(json, ".listHashes.single"));
        assertEq(keccak256(joinIds(new string[](0))), vm.parseJsonBytes32(json, ".listHashes.empty"));
        // the "|" delimiter is load-bearing: ["ab"] must differ from ["a","b"]
        string[] memory ab = new string[](1);
        ab[0] = "ab";
        string[] memory a_b = new string[](2);
        a_b[0] = "a";
        a_b[1] = "b";
        assertEq(keccak256(joinIds(ab)), vm.parseJsonBytes32(json, ".listHashes.ab"));
        assertEq(keccak256(joinIds(a_b)), vm.parseJsonBytes32(json, ".listHashes.a_b"));
        assertNotEq(keccak256(joinIds(ab)), keccak256(joinIds(a_b)));
    }

    // --- digests: Solidity abi.encode == TS AbiCoder ---
    function test_digestsMatch() public view {
        assertEq(
            createPlanDigest(
                fixtureAgent,
                uint96(vm.parseJsonUint(json, ".createPlan.capPerExec")),
                uint96(vm.parseJsonUint(json, ".createPlan.capPerPeriod")),
                uint32(vm.parseJsonUint(json, ".createPlan.periodSecs")),
                vm.parseJsonBytes32(json, ".createPlan.assetListHash"),
                vm.parseJsonUint(json, ".createPlan.nonce")
            ),
            vm.parseJsonBytes32(json, ".createPlan.digest")
        );
        assertEq(
            revokePlanDigest(
                vm.parseJsonUint(json, ".revokePlan.id"), vm.parseJsonUint(json, ".revokePlan.nonce")
            ),
            vm.parseJsonBytes32(json, ".revokePlan.digest")
        );
        assertEq(
            revokeAllDigest(vm.parseJsonUint(json, ".revokeAll.nonce")),
            vm.parseJsonBytes32(json, ".revokeAll.digest")
        );
        assertEq(
            enrollEstateDigest(
                vm.parseJsonBytes32(json, ".enrollEstate.beneficiaryHash"),
                uint64(vm.parseJsonUint(json, ".enrollEstate.inactivitySecs")),
                vm.parseJsonUint(json, ".enrollEstate.nonce")
            ),
            vm.parseJsonBytes32(json, ".enrollEstate.digest")
        );
    }

    // --- EIP-191 recovery of the TS signatures ---
    function test_signaturesRecoverToFixtureSigner() public view {
        string[4] memory ops = ["createPlan", "revokePlan", "revokeAll", "enrollEstate"];
        for (uint256 i = 0; i < ops.length; i++) {
            bytes32 digest = vm.parseJsonBytes32(json, string.concat(".", ops[i], ".digest"));
            bytes memory sig = vm.parseJsonBytes(json, string.concat(".", ops[i], ".sig"));
            (bytes32 r, bytes32 s, uint8 v) = _split(sig);
            assertEq(ecrecover(prefixed(digest), v, r, s), fixtureSigner, ops[i]);
        }
    }

    // --- end to end: TS-signed payloads accepted by the real bytecode ---
    function test_endToEnd_tsSignaturesDriveTheContract() public {
        string[] memory ids = vm.parseJsonStringArray(json, ".createPlan.assetIdsSorted");
        uint256 id = policy.createPlan(
            fixtureSigner,
            uint96(vm.parseJsonUint(json, ".createPlan.capPerExec")),
            uint96(vm.parseJsonUint(json, ".createPlan.capPerPeriod")),
            uint32(vm.parseJsonUint(json, ".createPlan.periodSecs")),
            vm.parseJsonBytes32(json, ".createPlan.assetListHash"),
            ids,
            vm.parseJsonUint(json, ".createPlan.nonce"),
            vm.parseJsonBytes(json, ".createPlan.sig")
        );
        assertEq(id, vm.parseJsonUint(json, ".revokePlan.id"));
        assertEq(planStatus(id), uint8(RetenixPolicy.PlanStatus.Active));
        // the allowlist was populated from the plaintext ids
        vm.prank(fixtureAgent);
        policy.recordExecution(id, uint96(vm.parseJsonUint(json, ".usd6.usd15")), SPYX);

        policy.revokePlanFor(
            id, vm.parseJsonUint(json, ".revokePlan.nonce"), vm.parseJsonBytes(json, ".revokePlan.sig")
        );
        assertEq(planStatus(id), uint8(RetenixPolicy.PlanStatus.Revoked));

        policy.revokeAll(
            fixtureSigner, vm.parseJsonUint(json, ".revokeAll.nonce"), vm.parseJsonBytes(json, ".revokeAll.sig")
        );

        policy.enrollEstate(
            fixtureSigner,
            vm.parseJsonBytes32(json, ".enrollEstate.beneficiaryHash"),
            uint64(vm.parseJsonUint(json, ".enrollEstate.inactivitySecs")),
            vm.parseJsonUint(json, ".enrollEstate.nonce"),
            vm.parseJsonBytes(json, ".enrollEstate.sig")
        );
        assertEq(
            uint8(policy.estateStatus(fixtureSigner)), uint8(RetenixPolicy.EstateStatus.Enrolled)
        );
    }

    /// The fixture signatures are domain-bound: on any other chain id the same
    /// payload must be rejected (no cross-chain replay).
    function test_fixtureSignaturesRejectedOffDomain() public {
        vm.chainId(42161); // One, not the fixture's Sepolia
        string[] memory ids = vm.parseJsonStringArray(json, ".createPlan.assetIdsSorted");
        vm.expectRevert(RetenixPolicy.BadSignature.selector);
        policy.createPlan(
            fixtureSigner,
            uint96(vm.parseJsonUint(json, ".createPlan.capPerExec")),
            uint96(vm.parseJsonUint(json, ".createPlan.capPerPeriod")),
            uint32(vm.parseJsonUint(json, ".createPlan.periodSecs")),
            vm.parseJsonBytes32(json, ".createPlan.assetListHash"),
            ids,
            vm.parseJsonUint(json, ".createPlan.nonce"),
            vm.parseJsonBytes(json, ".createPlan.sig")
        );
    }

    function _split(bytes memory sig) internal pure returns (bytes32 r, bytes32 s, uint8 v) {
        require(sig.length == 65, "sig length");
        assembly {
            r := mload(add(sig, 0x20))
            s := mload(add(sig, 0x40))
            v := byte(0, mload(add(sig, 0x60)))
        }
        if (v < 27) v += 27;
    }
}
