import { AbiCoder, getBytes, keccak256 } from "ethers";

/**
 * Relayed-auth digests for RetenixPolicy (doc 07) — the TS half of the
 * two-implementation library. The Solidity half lives in-contract; the two are
 * cross-tested with fixture vectors (contracts/test/fixtures/policy-vectors.json,
 * generated by packages/registry/scripts/gen-policy-vectors.ts).
 *
 * PROPOSED format (doc 07 Final ABI comment): EIP-191 personal_sign over
 *   keccak256(abi.encode(chainid, verifyingContract, "<op>", ...params, nonce))
 * The owner signs the 32-byte digest as a message (getBytes → personal_sign),
 * the relayer submits, and the contract recovers via ecrecover over the
 * "\x19Ethereum Signed Message:\n32"-prefixed digest. `authNonces[owner]` is
 * sequential — read it from the contract before building a digest.
 *
 * Future consumer: apps/web/server/lib/relay.ts (modules 10/13/14). Client and
 * server MUST both use these builders so the signed bytes can never drift.
 */

const coder = AbiCoder.defaultAbiCoder();

export interface PolicyDomain {
  /** chain the contract lives on (42161 prod / 421614 dev) */
  chainId: number | bigint;
  /** deployed RetenixPolicy address */
  contract: string;
}

export const createPlanDigest = (
  d: PolicyDomain,
  p: {
    agent: string;
    capPerExec: bigint; // usd6
    capPerPeriod: bigint; // usd6
    periodSecs: number;
    assetListHash: string; // packages/registry assetListHash — never reimplement
    nonce: bigint;
  },
): string =>
  keccak256(
    coder.encode(
      ["uint256", "address", "string", "address", "uint96", "uint96", "uint32", "bytes32", "uint256"],
      [d.chainId, d.contract, "createPlan", p.agent, p.capPerExec, p.capPerPeriod, p.periodSecs, p.assetListHash, p.nonce],
    ),
  );

export const revokePlanDigest = (d: PolicyDomain, p: { id: bigint; nonce: bigint }): string =>
  keccak256(
    coder.encode(
      ["uint256", "address", "string", "uint256", "uint256"],
      [d.chainId, d.contract, "revokePlan", p.id, p.nonce],
    ),
  );

export const revokeAllDigest = (d: PolicyDomain, p: { nonce: bigint }): string =>
  keccak256(
    coder.encode(
      ["uint256", "address", "string", "uint256"],
      [d.chainId, d.contract, "revokeAll", p.nonce],
    ),
  );

export const enrollEstateDigest = (
  d: PolicyDomain,
  p: { beneficiaryHash: string; inactivitySecs: bigint; nonce: bigint },
): string =>
  keccak256(
    coder.encode(
      ["uint256", "address", "string", "bytes32", "uint64", "uint256"],
      [d.chainId, d.contract, "enrollEstate", p.beneficiaryHash, p.inactivitySecs, p.nonce],
    ),
  );

/** Minimal signer surface — satisfied by ethers Wallet and Magic-backed signers. */
export interface DigestSigner {
  signMessage(message: Uint8Array): Promise<string>;
}

/** personal_sign over the 32 digest BYTES (not the hex string). */
export const signPolicyDigest = (signer: DigestSigner, digest: string): Promise<string> =>
  signer.signMessage(getBytes(digest));
